### ISSUE TITLE
docker ubuntu /sbin/init

### ISSUE THREAD

**Issue by gygelly** [makinacorpus/vms#3]
Hello, I'm very interested in a docker ubuntu image with working upstart. 
I downloaded your project and used ./make.sh to build an ubuntu_precise and ubuntu_saucy image. Unfortunately, when I run them using:
`docker run -i -t -d makinacorpus/ubuntu_precise /sbin/init`
the container appears to start correctly, but none of the services upstart is supposed to start start automatically: I have to manually start them with `service start`.

In this way, the images built behave just like the base docker ubuntu images.

Is there something I'm missing? I was under the impression this would work with your images.

My dev environment:
Ubuntu 14.04 x64
docker was run with -e lxc

**Comment by kiorky** [comment]
you problem is then not upstart but the upstart scripts, when one fails, all fail, so to investigate you ll have to look in the container /var/log/upstart for possible failures
