### ISSUE TITLE
Does not work with vagrant 1.8.6

### ISSUE THREAD

**Issue by pounard** [makinacorpus/vms#7]
I got a vagrant surprise update on my archlinux, with 1.8.6 it wasn't working, downgrading to 1.8.5 and after a reboot, everything went fine back.

Problem was with IP's, the guest VM IP address (10.3.x.x) was not properly set.

**Comment by kiorky** [comment]
look corp tracker instead of spam.

**Comment by kiorky** [comment]
btw, yes, with @regilero we now those problems, for the private ip stuff, i had some sucesses, but a lot of fails, and this is tied to numerous bugs in the vagrant network plugins and ubuntu >=16.04 (AS a guest)

**Comment by kiorky** [comment]
What is surprising is that normally, as soon as a VM is setup (the /etc/network/interfaces is in order, as /etc/hosts), the VM should work as-is, are you sure you were using a running vm ?
